services:
  postgres:
    image: postgres:16-alpine
    container_name: agency_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: agency_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: agency_backend
    restart: always
    ports:
      - '5000:5000'
    environment:
      PORT: 5000
      NODE_ENV: production
      DATABASE_URL: "postgresql://postgres:postgrespassword@postgres:5432/agency_db?schema=public"
      JWT_ACCESS_SECRET: "prod-access-secret-32-chars-long-agency-assessment"
      JWT_REFRESH_SECRET: "prod-refresh-secret-32-chars-long-agency-assessment"
      CLIENT_URL: "http://localhost:5173"
    depends_on:
      - postgres

volumes:
  pgdata:
